apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_USER: admin
  MONGO_PASSWORD: strongpassword
  MONGO_URI: mongodb://admin:strongpassword@mongo:27017/todos?authSource=admin

